# Data storage and formats

In this notebook, we will learn about cloud storage and the Parquet format for storing tabular data.

---

Large datasets are typically stored on cloud object storage, that are designed to:
* store massive files,
* for long periods of time, and
* support parallelism in I/O operations.

Some of the largest providers of object storage are Amazon S3, Google Cloud Storage, and Azure Data Lake. In this tutorial, we're accessing data stored on Google Cloud Storage.

## Data has gravity

It's almost always better to move your computations to the data (compared to vice-versa). This is because data transfers are typically the highest bottlenecks, so downloading data to a local machine and then computing will be very slow, even for small amounts of data.

If your data is stored locally (for example, on hard drives), you should consider a local / on-premise cluster setup.

If your data is stored on the cloud, you can spin up a cluster on the same cloud. Note that moving data between cloud providers can also get challenging.

## Cloud storage as file systems

Libraries like `s3fs` and `gcsfs` allow you to access the data with a Python interface. In this tutorial, [we're using `gcsfs`](https://gcsfs.readthedocs.io/en/latest/):

In [2]:
import gcsfs

In [3]:
fs = gcsfs.GCSFileSystem(token='anon')

We're accessing public datasets, but you can also pass tokens for private buckets: `GCSFileSystem(token=your_token)`.

You can now take a look at the storage bucket in a file-system like interface:

In [1]:
import os
print(os.listdir('.'))

['.config', 'sample_data']

In [4]:
import pandas as pd
import requests
import zipfile
import io
import os

# Link dữ liệu tháng 1/2022
url = (
    "https://transtats.bts.gov/PREZIP/"
    "On_Time_Reporting_Carrier_On_Time_Performance_"
    "1987_present_2022_1.zip"
)

# Tải file ZIP
r = requests.get(url)
r.raise_for_status()

# Giải nén CSV vào /content
with zipfile.ZipFile(io.BytesIO(r.content)) as z:
    csv_file = [f for f in z.namelist() if f.endswith(".csv")][0]
    z.extract(csv_file, "/content")

# Đường dẫn file CSV
csv_path = os.path.join("/content", csv_file)

print("Đã tải file:", csv_path)

# Đọc dữ liệu bằng Pandas
df = pd.read_csv(
    csv_path,
    low_memory=False
)

# Hiển thị 5 dòng đầu
df.head()

Đã tải file: /content/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2022,1,1,14,5,2022-01-14,YX,20452,YX,N119HQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,1,1,15,6,2022-01-15,YX,20452,YX,N122HQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,1,1,16,7,2022-01-16,YX,20452,YX,N412YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,1,1,17,1,2022-01-17,YX,20452,YX,N405YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,1,1,18,2,2022-01-18,YX,20452,YX,N420YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 💻 Your turn: Open the above folders to view the contents

In [5]:
# Your code here. When ready, click on the three dots below for the solution.
import os

os.listdir("/content")

['.config',
 'On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv',
 'sample_data']

### 💻 Your turn: Read a line from one of the CSV files

Hint: How would you do it if it was a local file?

In [6]:
# Your code here. When ready, click on the three dots below for the solution.
with open(
    "On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv",
    "r"
) as f:
    print(f.readline())

"Year","Quarter","Month","DayofMonth","DayOfWeek","FlightDate","Reporting_Airline","DOT_ID_Reporting_Airline","IATA_CODE_Reporting_Airline","Tail_Number","Flight_Number_Reporting_Airline","OriginAirportID","OriginAirportSeqID","OriginCityMarketID","Origin","OriginCityName","OriginState","OriginStateFips","OriginStateName","OriginWac","DestAirportID","DestAirportSeqID","DestCityMarketID","Dest","DestCityName","DestState","DestStateFips","DestStateName","DestWac","CRSDepTime","DepTime","DepDelay","DepDelayMinutes","DepDel15","DepartureDelayGroups","DepTimeBlk","TaxiOut","WheelsOff","WheelsOn","TaxiIn","CRSArrTime","ArrTime","ArrDelay","ArrDelayMinutes","ArrDel15","ArrivalDelayGroups","ArrTimeBlk","Cancelled","CancellationCode","Diverted","CRSElapsedTime","ActualElapsedTime","AirTime","Flights","Distance","DistanceGroup","CarrierDelay","WeatherDelay","NASDelay","SecurityDelay","LateAircraftDelay","FirstDepTime","TotalAddGTime","LongestAddGTime","DivAirportLandings","DivReachedDest","DivActualElapsedTime","DivArrDelay","DivDistance","Div1Airport","Div1AirportID","Div1AirportSeqID","Div1WheelsOn","Div1TotalGTime","Div1LongestGTime","Div1WheelsOff","Div1TailNum","Div2Airport","Div2AirportID","Div2AirportSeqID","Div2WheelsOn","Div2TotalGTime","Div2LongestGTime","Div2WheelsOff","Div2TailNum","Div3Airport","Div3AirportID","Div3AirportSeqID","Div3WheelsOn","Div3TotalGTime","Div3LongestGTime","Div3WheelsOff","Div3TailNum","Div4Airport","Div4AirportID","Div4AirportSeqID","Div4WheelsOn","Div4TotalGTime","Div4LongestGTime","Div4WheelsOff","Div4TailNum","Div5Airport","Div5AirportID","Div5AirportSeqID","Div5WheelsOn","Div5TotalGTime","Div5LongestGTime","Div5WheelsOff","Div5TailNum",

In [7]:
with open("On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv", "r") as f:
    print(f.readline())

"Year","Quarter","Month","DayofMonth","DayOfWeek","FlightDate","Reporting_Airline","DOT_ID_Reporting_Airline","IATA_CODE_Reporting_Airline","Tail_Number","Flight_Number_Reporting_Airline","OriginAirportID","OriginAirportSeqID","OriginCityMarketID","Origin","OriginCityName","OriginState","OriginStateFips","OriginStateName","OriginWac","DestAirportID","DestAirportSeqID","DestCityMarketID","Dest","DestCityName","DestState","DestStateFips","DestStateName","DestWac","CRSDepTime","DepTime","DepDelay","DepDelayMinutes","DepDel15","DepartureDelayGroups","DepTimeBlk","TaxiOut","WheelsOff","WheelsOn","TaxiIn","CRSArrTime","ArrTime","ArrDelay","ArrDelayMinutes","ArrDel15","ArrivalDelayGroups","ArrTimeBlk","Cancelled","CancellationCode","Diverted","CRSElapsedTime","ActualElapsedTime","AirTime","Flights","Distance","DistanceGroup","CarrierDelay","WeatherDelay","NASDelay","SecurityDelay","LateAircraftDelay","FirstDepTime","TotalAddGTime","LongestAddGTime","DivAirportLandings","DivReachedDest","DivActualElapsedTime","DivArrDelay","DivDistance","Div1Airport","Div1AirportID","Div1AirportSeqID","Div1WheelsOn","Div1TotalGTime","Div1LongestGTime","Div1WheelsOff","Div1TailNum","Div2Airport","Div2AirportID","Div2AirportSeqID","Div2WheelsOn","Div2TotalGTime","Div2LongestGTime","Div2WheelsOff","Div2TailNum","Div3Airport","Div3AirportID","Div3AirportSeqID","Div3WheelsOn","Div3TotalGTime","Div3LongestGTime","Div3WheelsOff","Div3TailNum","Div4Airport","Div4AirportID","Div4AirportSeqID","Div4WheelsOn","Div4TotalGTime","Div4LongestGTime","Div4WheelsOff","Div4TailNum","Div5Airport","Div5AirportID","Div5AirportSeqID","Div5WheelsOn","Div5TotalGTime","Div5LongestGTime","Div5WheelsOff","Div5TailNum",

## Start a Dask Gateway cluster

This time, let's specify the various options explicitly:

In [8]:
!pip install -q dask-gateway

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.2 MB/s eta 0:00:00

In [9]:
from dask.distributed import Client, LocalCluster

# Khởi tạo Local Cluster ngay trên môi trường Google Colab
cluster = LocalCluster()
client = Client(cluster)

# Hiển thị Dashboard và thông tin client
client

INFO:distributed.http.proxy:To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
INFO:distributed.scheduler:State start
INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:43213
INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:8787/status
INFO:distributed.scheduler:Registering Worker plugin shuffle
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:38613'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:37229'
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:36955 name: 1
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:36955
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:46824
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:37189 name: 0
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:37189
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:46826
INFO:distributed.scheduler:Receive client connection: Client-ef8046f2-b6f9-11f1-89c4-0242ac1c000c
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:46840

Make sure to open the following plots: Cluster map, task stream, progress, and workers memory!

## CSV data format

We'll download the CSV files again, as we did in the previous notebook, note the time various operations take:

In [10]:
dtypes = {
    "ArrTime": "float64",
    "ArrivalDelayGroups": "float64",
    "CancellationCode": "object",
    "DepTime": "float64",
    "DepartureDelayGroups": "float64",
    "Div1Airport": "object",
    "Div1TailNum": "object",
    "Div2Airport": "object",
    "Div2TailNum": "object",
    "WheelsOff": "float64",
    "WheelsOn": "float64"
}

print("Đã tạo dtypes thành công")

Đã tạo dtypes thành công

In [11]:
import dask.dataframe as dd

In [12]:
%%time

ddf = dd.read_csv(
    "On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv",
    dtype=dtypes
)

CPU times: user 54.5 ms, sys: 3.99 ms, total: 58.5 ms
Wall time: 69 ms

In [13]:
%%time

ddf.head() # Wall time: 8.62 s

CPU times: user 725 ms, sys: 126 ms, total: 852 ms
Wall time: 12.1 s

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2022,1,1,14,5,2022-01-14,YX,20452,YX,N119HQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,1,1,15,6,2022-01-15,YX,20452,YX,N122HQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,1,1,16,7,2022-01-16,YX,20452,YX,N412YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,1,1,17,1,2022-01-17,YX,20452,YX,N405YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,1,1,18,2,2022-01-18,YX,20452,YX,N420YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
dtype={'ArrTime': 'float64',
       'ArrivalDelayGroups': 'float64',
       'CancellationCode': 'object',
       'DepTime': 'float64',
       'DepartureDelayGroups': 'float64',
       'Div1Airport': 'object',
       'Div1TailNum': 'object',
       'Div2Airport': 'object',
       'Div2TailNum': 'object',
       'WheelsOff': 'float64',
       'WheelsOn': 'float64'}

### 💻 Your turn: Compute the number of unique flights taken each year

Make sure to time it, and watch the dashboard plots!

In [15]:
# Your code here. When ready, click on the three dots below for the solution.
%%time

ddf.groupby('Year').Reporting_Airline.count().compute()

CPU times: user 835 ms, sys: 132 ms, total: 968 ms
Wall time: 14.7 s

Year
2022    537902
Name: Reporting_Airline, dtype: int64

In [16]:
ddf.groupby('Year').Reporting_Airline.count().compute()

Year
2022    537902
Name: Reporting_Airline, dtype: int64

In [17]:
import dask.dataframe as dd

# 1. Định nghĩa chính xác kiểu dữ liệu cho các cột bị lỗi
correct_dtypes = {
    'ArrTime': 'float64',
    'ArrivalDelayGroups': 'float64',
    'CancellationCode': 'object',
    'DepTime': 'float64',
    'DepartureDelayGroups': 'float64',
    'Div1Airport': 'object',
    'Div1TailNum': 'object',
    'Div2Airport': 'object',
    'Div2TailNum': 'object',
    'WheelsOff': 'float64',
    'WheelsOn': 'float64'
}

# 2. Đọc lại file CSV kèm theo dtype và assume_missing=True
ddf = dd.read_csv(
    "On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv",
    dtype=correct_dtypes,
    assume_missing=True
)

In [18]:
print(ddf.columns)

Index(['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate',
       'Reporting_Airline', 'DOT_ID_Reporting_Airline',
       'IATA_CODE_Reporting_Airline', 'Tail_Number',
       ...
       'Div4TailNum', 'Div5Airport', 'Div5AirportID', 'Div5AirportSeqID',
       'Div5WheelsOn', 'Div5TotalGTime', 'Div5LongestGTime', 'Div5WheelsOff',
       'Div5TailNum', 'Unnamed: 109'],
      dtype='object', length=110)

## Parquet data format

[Apache Parquet](https://parquet.apache.org/) is a columnar data format widely used for storing large tabular datasets.

### Parquet I/O

Parquet data is very efficient to store and access (i.e., compression and encoding), and stores metadata like data-types, column names, and ranges per file/partition.

In the following cells we read the full parquet dataset, notice how it's faster and that we did not need to explicitly share datatypes.

In [19]:
import dask.dataframe as dd

# Khai báo kiểu dữ liệu cho các cột dễ lỗi
dtypes_correct = {
    "ArrTime": "float64",
    "ArrivalDelayGroups": "float64",
    "CancellationCode": "object",
    "DepTime": "float64",
    "DepartureDelayGroups": "float64",
    "Div1Airport": "object",
    "Div1TailNum": "object",
    "Div2Airport": "object",
    "Div2TailNum": "object",
    "WheelsOff": "float64",
    "WheelsOn": "float64"
}

# Đọc CSV bằng Dask
ddf_csv = dd.read_csv(
    "On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv",
    dtype=dtypes_correct,
    assume_missing=True
)

# Chuyển sang Parquet
ddf_csv.to_parquet(
    "ontime_2022.parquet",
    write_index=False
)

print("Đã chuyển CSV sang Parquet thành công")

Đã chuyển CSV sang Parquet thành công

In [20]:
ddf_pq = dd.read_parquet("ontime_2022.parquet")

In [21]:
%%time

ddf_pq.head() # Wall time: 1.16 s

CPU times: user 65.7 ms, sys: 8.89 ms, total: 74.6 ms
Wall time: 748 ms

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2022.0,1.0,1.0,14.0,5.0,2022-01-14,YX,20452.0,YX,N119HQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022.0,1.0,1.0,15.0,6.0,2022-01-15,YX,20452.0,YX,N122HQ,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022.0,1.0,1.0,16.0,7.0,2022-01-16,YX,20452.0,YX,N412YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022.0,1.0,1.0,17.0,1.0,2022-01-17,YX,20452.0,YX,N405YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022.0,1.0,1.0,18.0,2.0,2022-01-18,YX,20452.0,YX,N420YX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 💻 Your turn: Perform same computation as earlier to compute the number of unique flights taken each year

Time it again and compare against the previous value!

In [22]:
# Your code here. When ready, click on the three dots below for the solution.
%%time

ddf_pq.groupby('Year').Reporting_Airline.count().compute()

CPU times: user 67.4 ms, sys: 1.38 ms, total: 68.8 ms
Wall time: 226 ms

Year
2022.0    537902
Name: Reporting_Airline, dtype: int64

In [23]:
%%time

ddf_pq.groupby('Year').Reporting_Airline.count().compute() # Wall time: 14.1 s

CPU times: user 56.9 ms, sys: 2.84 ms, total: 59.8 ms
Wall time: 186 ms

Year
2022.0    537902
Name: Reporting_Airline, dtype: int64

### Read specific columns

As a column-oriented format, you can decide to read only necessary columns, further improving efficiency:

In [24]:
ddf_pq_subset = dd.read_parquet(
    "ontime_2022.parquet",
    columns=['Year', 'Reporting_Airline']
)

In [25]:
%%time

ddf_pq_subset.groupby('Year').Reporting_Airline.count().compute() # Wall time: 12.9 s

CPU times: user 54 ms, sys: 377 µs, total: 54.4 ms
Wall time: 164 ms

Year
2022.0    537902
Name: Reporting_Airline, dtype: int64

### Partitioned storage

Parquet files can be stored with a partitioning schema that works best for your computation.

It's useful to take the time to partition your dataset based on your workflows (partition structure, as well as number of partitions). Dask can partition your DataFrame accordingly when you read the data.

Here, we've partitioned the dataset by `YEAR`:

Do 2 lệnh này bộ dataset quansight đã bị xóa hay bị dời đi nơi khác nên thay thế bằng bộ dataset Ontime và chức năng code cũng thay đổi

In [26]:
import os

os.listdir("ontime_2022.parquet")

['part.2.parquet', 'part.0.parquet', 'part.1.parquet']

Thay code trên thành

In [27]:
os.listdir("ontime_2022.parquet")

['part.2.parquet', 'part.0.parquet', 'part.1.parquet']

In [28]:
os.listdir("ontime_2022.parquet")

['part.2.parquet', 'part.0.parquet', 'part.1.parquet']

### Row-wise filtering

Parquet also stores the ranges of values present in each file and partition, so you can efficiently filter Parquet datasets row-wise while reading the data.

For example, consider we want to exclude 2020 because of its unique impact on the airline industry:

In [29]:
import dask.dataframe as dd

# Đọc duy nhất 2 cột và LỌC BỎ năm 2020 ngay lúc đọc file
ddf_pq_subset = dd.read_parquet(
    "ontime_2022.parquet",
    columns=['Year', 'Reporting_Airline'],
    filters=[[('Year', '!=', 2020)]]
)

In [30]:
ddf_pq_subset.groupby('Year').Reporting_Airline.count().compute()

Year
2022.0    537902
Name: Reporting_Airline, dtype: int64

#### 💻 Your turn: Groupby month instead of year, and only read+calculate unique flights for Q4 of each year

In [31]:
# Your code here. When ready, click on the three dots below for the solution.
import dask.dataframe as dd

ddf_pq_q4 = dd.read_parquet(
    "ontime_2022.parquet",
    columns=["Month", "Reporting_Airline"],
    filters=[[("Month", ">=", 10)]]
)

ddf_pq_q4.groupby(
    "Month"
).Reporting_Airline.count().compute()

Series([], Name: Reporting_Airline, dtype: int64)

In [32]:
import dask.dataframe as dd

# 1. Đọc dữ liệu từ file Parquet cục bộ, chỉ lấy dữ liệu các tháng từ 9 trở đi
ddf_pq_q4 = dd.read_parquet(
    "ontime_2022.parquet",
    columns=['Month', 'Reporting_Airline'],
    filters=[[('Month', '<=', 3)]]
)

# 2. Gom nhóm theo Month và đếm số chuyến bay
ddf_pq_q4.groupby('Month').Reporting_Airline.count().compute()

Month
1.0    537902
Name: Reporting_Airline, dtype: int64

## Convert from CSV to Parquet

You can convert CSV files to Parquet in two main ways:

- Dask (and pandas) have a `to_parquet()` function, you can also partition the data while converting.
- You can use powerful Parquet engines like [`pyarrow`](https://arrow.apache.org/docs/python/csv.htmlhttps://arrow.apache.org/docs/python/csv.html) or `fastparquet` directly (Dask and pandas use these engines internally)

```python

# You do not need to execute this code

import dask.dataframe as dd

dd.read_csv("path_to_csv_files_on_cloud_storage")
dd.to_parquet("path_to_cloud_storage_loaction", partition_by="")
```

We created the Parquet dataset using Dask, and our code is available in `scripts/csv_to_parquet.ipynb`.

## Notable mentions

* If you're working with multidimensional arrays, [Zarr](https://zarr.readthedocs.io/en/stable/index.html) is an excellent format to store chunked array data (similar to partitioning, but along multiple dimensions).
* If you expect your workflows to have SQL-like query operations, storing your data in [Snowflake](https://www.snowflake.com/en/) can be a good option.
* [Creating Disk Partitioned Lakes with Dask using partition_on](https://www.coiled.io/blog/dask-disk-partition-on), a blog post by Coiled, has some valuable best practices.

---
## Next →

[Big data analysis with Dask](./05-big-data-analysis-with-dask.ipynb)!