<img src="https://hvplot.holoviz.org/_static/logo_horizontal.svg" width="20%" align="right"/>

# Big data visualization with Dask and hvPlot

In this notebook, we'll learn to use the hvPlot APIs with Dask DataFrames.

---

## Reconnect to our Dask Cluster

In [1]:
!pip install dask-gateway

Requirement already satisfied: dask-gateway in /usr/local/lib/python3.13/dist-packages (2026.3.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.13/dist-packages (from dask-gateway) (3.14.3)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.13/dist-packages (from dask-gateway) (8.5.0)
Requirement already satisfied: dask>=2022.4.0 in /usr/local/lib/python3.13/dist-packages (from dask-gateway) (2026.8.0)
Requirement already satisfied: distributed>=2022.4.0 in /usr/local/lib/python3.13/dist-packages (from dask-gateway) (2026.8.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.13/dist-packages (from dask-gateway) (6.0.3)
Requirement already satisfied: tornado in /usr/local/lib/python3.13/dist-packages (from dask-gateway) (6.5.7)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2022.4.0->dask-gateway) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2022.4.0->dask-gateway) (2025.12.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2022.4.0->dask-gateway) (26.3)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2022.4.0->dask-gateway) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.13/dist-packages (from dask>=2022.4.0->dask-gateway) (0.12.1)
Requirement already satisfied: jinja2>=2.10.3 in /usr/local/lib/python3.13/dist-packages (from distributed>=2022.4.0->dask-gateway) (3.1.6)
Requirement already satisfied: locket>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from distributed>=2022.4.0->dask-gateway) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.13/dist-packages (from distributed>=2022.4.0->dask-gateway) (1.2.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.13/dist-packages (from distributed>=2022.4.0->dask-gateway) (5.9.5)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.13/dist-packages (from distributed>=2022.4.0->dask-gateway) (2.4.0)
Requirement already satisfied: tblib!=3.2.0,!=3.2.1,>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from distributed>=2022.4.0->dask-gateway) (3.2.2)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.13/dist-packages (from distributed>=2022.4.0->dask-gateway) (3.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->dask-gateway) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->dask-gateway) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->dask-gateway) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp->dask-gateway) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp->dask-gateway) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->dask-gateway) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp->dask-gateway) (1.24.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2>=2.10.3->distributed>=2022.4.0->dask-gateway) (3.0.3)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.13/dist-packages (from yarl<2.0,>=1.17.0->aiohttp->dask-gateway) (3.19)

In [2]:
import dask_gateway
import dask.dataframe as dd

In [3]:
from dask.distributed import Client, LocalCluster

# Khởi tạo cụm quản lý cục bộ trên Colab
cluster = LocalCluster()

# Kết nối client điều khiển
client = Client(cluster)

# Hiển thị thông tin quản lý và Dask Dashboard
cluster

INFO:distributed.http.proxy:To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
INFO:distributed.scheduler:State start
INFO:distributed.diskutils:Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-puidi4zk', purging
INFO:distributed.scheduler:  Scheduler at:     tcp://127.0.0.1:37475
INFO:distributed.scheduler:  dashboard at:  http://127.0.0.1:8787/status
INFO:distributed.scheduler:Registering Worker plugin shuffle
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:34777'
INFO:distributed.nanny:        Start Nanny at: 'tcp://127.0.0.1:37879'
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:41475 name: 0
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:41475
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:58074
INFO:distributed.scheduler:Register worker addr: tcp://127.0.0.1:37867 name: 1
INFO:distributed.scheduler:Starting worker compute stream, tcp://127.0.0.1:37867
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:58080
INFO:distributed.scheduler:Receive client connection: Client-a3b979d5-b58f-11f1-894a-0242ac1c000c
INFO:distributed.core:Starting established connection to tcp://127.0.0.1:58092

LocalCluster(0107d27b, 'tcp://127.0.0.1:37475', workers=2, threads=2, memory=12.67 GiB)

## Load a subset of columns

In [4]:
columns = [
    'YEAR', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'OP_CARRIER',
    'TAIL_NUM', 'OP_CARRIER_FL_NUM', 'ORIGIN', 'DEST', 'CRS_DEP_TIME',
    'DEP_TIME', 'DEP_DELAY', 'ARR_TIME', 'ARR_DELAY', 'CANCELLED',
    'CANCELLATION_CODE', 'DIVERTED', 'AIR_TIME', 'FLIGHTS', 'DISTANCE',
    'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY',
    'LATE_AIRCRAFT_DELAY', 'DIV_ARR_DELAY'
]

In [5]:
import dask.dataframe as dd
import requests
import zipfile
import io
import os

# 1. Tải dữ liệu tháng 1/2022
url = (
    "https://transtats.bts.gov/PREZIP/"
    "On_Time_Reporting_Carrier_On_Time_Performance_"
    "1987_present_2022_1.zip"
)

r = requests.get(url)
r.raise_for_status()

# 2. Giải nén CSV vào /content
with zipfile.ZipFile(io.BytesIO(r.content)) as z:
    csv_file = [f for f in z.namelist() if f.endswith(".csv")][0]
    z.extract(csv_file, "/content")

csv_path = os.path.join("/content", csv_file)

print("Đã tải file:")
print(csv_path)

# 3. Các cột dùng trong bài 06
columns = [
    'Year', 'Month', 'DayofMonth', 'DayOfWeek',
    'FlightDate', 'Reporting_Airline',
    'Tail_Number', 'Flight_Number_Reporting_Airline',
    'Origin', 'Dest', 'CRSDepTime',
    'DepTime', 'DepDelay',
    'ArrTime', 'ArrDelay',
    'Cancelled', 'CancellationCode',
    'Diverted', 'AirTime',
    'Flights', 'Distance',
    'CarrierDelay', 'WeatherDelay',
    'NASDelay', 'SecurityDelay',
    'LateAircraftDelay'
]

# 4. Đọc bằng Dask
flights = dd.read_csv(
    csv_path,
    usecols=lambda col: col in columns,
    dtype={
        'CancellationCode': 'object',
        'FlightDate': 'string',
        'ArrTime': 'float64',
        'ArrDelay': 'float64',
        'DepTime': 'float64',
        'DepDelay': 'float64',
        'Distance': 'float64'
    },
    assume_missing=True
)

# 5. Xem 5 dòng đầu
flights.head()

Đã tải file:
/content/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv

,Year,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,Origin,Dest,...,CancellationCode,Diverted,AirTime,Flights,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2022.0,1.0,14.0,5.0,2022-01-14,YX,N119HQ,4879.0,CMH,DCA,...,<NA>,0.0,63.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
1,2022.0,1.0,15.0,6.0,2022-01-15,YX,N122HQ,4879.0,CMH,DCA,...,<NA>,0.0,50.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
2,2022.0,1.0,16.0,7.0,2022-01-16,YX,N412YX,4879.0,CMH,DCA,...,<NA>,0.0,53.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
3,2022.0,1.0,17.0,1.0,2022-01-17,YX,N405YX,4879.0,CMH,DCA,...,<NA>,0.0,56.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
4,2022.0,1.0,18.0,2.0,2022-01-18,YX,N420YX,4879.0,CMH,DCA,...,<NA>,0.0,48.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN

In [6]:
flights.head()

,Year,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,Origin,Dest,...,CancellationCode,Diverted,AirTime,Flights,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2022.0,1.0,14.0,5.0,2022-01-14,YX,N119HQ,4879.0,CMH,DCA,...,<NA>,0.0,63.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
1,2022.0,1.0,15.0,6.0,2022-01-15,YX,N122HQ,4879.0,CMH,DCA,...,<NA>,0.0,50.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
2,2022.0,1.0,16.0,7.0,2022-01-16,YX,N412YX,4879.0,CMH,DCA,...,<NA>,0.0,53.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
3,2022.0,1.0,17.0,1.0,2022-01-17,YX,N405YX,4879.0,CMH,DCA,...,<NA>,0.0,56.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
4,2022.0,1.0,18.0,2.0,2022-01-18,YX,N420YX,4879.0,CMH,DCA,...,<NA>,0.0,48.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN

## hvPlot + Dask

To use hvPlot's build in Dask integration, we need to switch out:

`import hvplot.pandas` for `import hvplot.dask`

In [7]:
!pip install jupyter_bokeh datashader hvplot

Requirement already satisfied: jupyter_bokeh in /usr/local/lib/python3.13/dist-packages (4.1.0)
Requirement already satisfied: datashader in /usr/local/lib/python3.13/dist-packages (0.19.1)
Requirement already satisfied: hvplot in /usr/local/lib/python3.13/dist-packages (0.12.2)
Requirement already satisfied: bokeh==3.* in /usr/local/lib/python3.13/dist-packages (from jupyter_bokeh) (3.8.2)
Requirement already satisfied: ipywidgets==8.* in /usr/local/lib/python3.13/dist-packages (from jupyter_bokeh) (8.1.9)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (2.25.0)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (2.1.3)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (26.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (2.2.3)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (6.5.7)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.13/dist-packages (from bokeh==3.*->jupyter_bokeh) (2026.3.0)
Requirement already satisfied: comm>=0.1.3 in /usr/local/lib/python3.13/dist-packages (from ipywidgets==8.*->jupyter_bokeh) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /usr/local/lib/python3.13/dist-packages (from ipywidgets==8.*->jupyter_bokeh) (7.34.0)
Requirement already satisfied: traitlets>=4.3.1 in /usr/local/lib/python3.13/dist-packages (from ipywidgets==8.*->jupyter_bokeh) (5.7.1)
Requirement already satisfied: widgetsnbextension~=4.0.16 in /usr/local/lib/python3.13/dist-packages (from ipywidgets==8.*->jupyter_bokeh) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in /usr/local/lib/python3.13/dist-packages (from ipywidgets==8.*->jupyter_bokeh) (3.0.17)
Requirement already satisfied: colorcet in /usr/local/lib/python3.13/dist-packages (from datashader) (3.2.1)
Requirement already satisfied: multipledispatch in /usr/local/lib/python3.13/dist-packages (from datashader) (1.0.0)
Requirement already satisfied: numba in /usr/local/lib/python3.13/dist-packages (from datashader) (0.61.2)
Requirement already satisfied: param in /usr/local/lib/python3.13/dist-packages (from datashader) (2.4.1)
Requirement already satisfied: pyct in /usr/local/lib/python3.13/dist-packages (from datashader) (0.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from datashader) (2.32.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from datashader) (1.16.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.13/dist-packages (from datashader) (0.12.1)
Requirement already satisfied: xarray in /usr/local/lib/python3.13/dist-packages (from datashader) (2025.12.0)
Requirement already satisfied: holoviews>=1.19.0 in /usr/local/lib/python3.13/dist-packages (from hvplot) (1.23.2)
Requirement already satisfied: panel>=1.0 in /usr/local/lib/python3.13/dist-packages (from hvplot) (1.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.19.0->hvplot) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.19.0->hvplot) (3.0.6)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->bokeh==3.*->jupyter_bokeh) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->bokeh==3.*->jupyter_bokeh) (2026.3)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (2.2.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (3.10.3)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (0.6.1)
Requirement already satisfied: nh3 in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (0.3.7)
Requirement already satisfied: panel-material-ui>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (0.14.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (4.67.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (4.16.0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba->datashader) (0.44.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->datashader) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->datashader) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->datashader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->datashader) (2026.7.22)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (80.10.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.20.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (3.0.53)
Requirement already satisfied: pygments in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (2.21.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.13/dist-packages (from ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from Jinja2>=2.9->bokeh==3.*->jupyter_bokeh) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->holoviews>=1.19.0->hvplot) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py->panel>=1.0->hvplot) (0.1.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.13/dist-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.13/dist-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.7.0)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.13/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=6.1.0->ipywidgets==8.*->jupyter_bokeh) (0.8.3)

In [8]:
!pip install hvplot

Requirement already satisfied: hvplot in /usr/local/lib/python3.13/dist-packages (0.12.2)
Requirement already satisfied: bokeh>=3.1 in /usr/local/lib/python3.13/dist-packages (from hvplot) (3.8.2)
Requirement already satisfied: colorcet>=2 in /usr/local/lib/python3.13/dist-packages (from hvplot) (3.2.1)
Requirement already satisfied: holoviews>=1.19.0 in /usr/local/lib/python3.13/dist-packages (from hvplot) (1.23.2)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.13/dist-packages (from hvplot) (2.1.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from hvplot) (26.3)
Requirement already satisfied: pandas>=1.3 in /usr/local/lib/python3.13/dist-packages (from hvplot) (2.2.3)
Requirement already satisfied: panel>=1.0 in /usr/local/lib/python3.13/dist-packages (from hvplot) (1.9.4)
Requirement already satisfied: param<3.0,>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from hvplot) (2.4.1)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->hvplot) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->hvplot) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->hvplot) (2.25.0)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->hvplot) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->hvplot) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->hvplot) (6.5.7)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.13/dist-packages (from bokeh>=3.1->hvplot) (2026.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.19.0->hvplot) (2.9.0.post0)
Requirement already satisfied: pyviz-comms>=2.1 in /usr/local/lib/python3.13/dist-packages (from holoviews>=1.19.0->hvplot) (3.0.6)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.3->hvplot) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.3->hvplot) (2026.3)
Requirement already satisfied: linkify-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (2.2.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (3.10.3)
Requirement already satisfied: markdown-it-py in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (4.2.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (0.6.1)
Requirement already satisfied: nh3 in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (0.3.7)
Requirement already satisfied: panel-material-ui>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (0.14.2)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (4.67.3)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.13/dist-packages (from panel>=1.0->hvplot) (4.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from Jinja2>=2.9->bokeh>=3.1->hvplot) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->holoviews>=1.19.0->hvplot) (1.17.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py->panel>=1.0->hvplot) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.0->hvplot) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.0->hvplot) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.0->hvplot) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->panel>=1.0->hvplot) (2026.7.22)

In [9]:
!pip install bokeh

Requirement already satisfied: bokeh in /usr/local/lib/python3.13/dist-packages (3.8.2)
Requirement already satisfied: Jinja2>=2.9 in /usr/local/lib/python3.13/dist-packages (from bokeh) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in /usr/local/lib/python3.13/dist-packages (from bokeh) (1.3.3)
Requirement already satisfied: narwhals>=1.13 in /usr/local/lib/python3.13/dist-packages (from bokeh) (2.25.0)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.13/dist-packages (from bokeh) (2.1.3)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.13/dist-packages (from bokeh) (26.3)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.13/dist-packages (from bokeh) (2.2.3)
Requirement already satisfied: pillow>=7.1.0 in /usr/local/lib/python3.13/dist-packages (from bokeh) (11.3.0)
Requirement already satisfied: PyYAML>=3.10 in /usr/local/lib/python3.13/dist-packages (from bokeh) (6.0.3)
Requirement already satisfied: tornado>=6.2 in /usr/local/lib/python3.13/dist-packages (from bokeh) (6.5.7)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.13/dist-packages (from bokeh) (2026.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from Jinja2>=2.9->bokeh) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->bokeh) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->bokeh) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=1.2->bokeh) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2->bokeh) (1.17.0)

In [10]:
import hvplot.dask
hvplot.extension('bokeh')

### Plot the departure delay per day for the entire dataset

In [11]:
flights.groupby('FlightDate')['DepDelay'].count().hvplot()

WARNING:distributed.shuffle._scheduler_plugin:Shuffle 0bcd850a2cebef12981dcd7a052d3c50 initialized by task ('shuffle-transfer-0bcd850a2cebef12981dcd7a052d3c50', 0) executed on worker tcp://127.0.0.1:37867
WARNING:distributed.shuffle._scheduler_plugin:Shuffle 0bcd850a2cebef12981dcd7a052d3c50 deactivated due to stimulus 'task-finished-1789976541.6498528'
WARNING:distributed.shuffle._scheduler_plugin:Shuffle 1279972f34f5851cf099025c98b13766 initialized by task ('shuffle-transfer-1279972f34f5851cf099025c98b13766', 0) executed on worker tcp://127.0.0.1:37867
WARNING:distributed.shuffle._scheduler_plugin:Shuffle 1279972f34f5851cf099025c98b13766 deactivated due to stimulus 'task-finished-1789976555.5167267'

:Curve   [FlightDate]   (DepDelay)

### 💻 Your turn: Visualize the weekly distribution of the mean of any variable in the datasets

You can any plot type from the [hvPlot Gallery](https://hvplot.holoviz.org/reference/index.html)

In [12]:
# Your code here. When ready, click on the three dots below for the solution.
flights.groupby('DayOfWeek')['ArrDelay'].mean().hvplot.scatter(
    x='DayOfWeek',
    y='ArrDelay'
)

:Scatter   [DayOfWeek]   (ArrDelay)

In [13]:
flights.groupby('DayOfWeek')['ArrDelay'].mean().hvplot.scatter(x="DayOfWeek", y='ArrDelay')

:Scatter   [DayOfWeek]   (ArrDelay)

## Plotting large datasets

In the above visualization of daily counts we saw a bunch of compute happening before we saw the plot appear. But after it was generated, panning and zooming did not cause any new Dask computes.

This is because the final dataset after the groupby is only about `20 years * 365 days` long, so it fits completely in memory.

Now let's look at the entire dataset:

In [14]:
print(f"The full dataset has {len(flights)/1e6:2} million rows")

The full dataset has 0.537902 million rows

If we try and send these many data points to the browser for visualization in a plot, the browser would run out of memory and crash.

<img src="images/datashader.svg" width="30%" align="right">

The solution for this is to take advantage of the fact that the output plot has a fixed resolution in terms of number of pixels. A 600x400 image has 240,000 pixels. This means that if we plotted 125 million points on the these pixels, most would overlay each other and not be visible. Instead, we pre-render or rasterize the data and shade in a manner that maintains an accurate the distribution of your data.

We do this via the hvPlot integration with **Datashader**.

We will use a smaller dataset for the next few examples for quick outputs. These examples will work with the full dataset, but will take a bit longer to run with the 10 computer nodes we are currently using for this tutorial.

In [15]:
import dask.dataframe as dd

# Đọc file CSV bằng các tham số chuẩn của Dask CSV
flights = dd.read_csv(
    "/content/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1*",
    usecols=lambda col: col in columns, # Lọc cột
    dtype={'CancellationCode': 'object'},
    assume_missing=True
)

# Nếu muốn lọc năm > 2017, hãy dùng cú pháp lọc trực tiếp của DataFrame
flights = flights[flights['Year'] > 2017]

In [16]:
flights.head()

,Year,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,Origin,Dest,...,CancellationCode,Diverted,AirTime,Flights,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2022.0,1.0,14.0,5.0,2022-01-14,YX,N119HQ,4879.0,CMH,DCA,...,<NA>,0.0,63.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
1,2022.0,1.0,15.0,6.0,2022-01-15,YX,N122HQ,4879.0,CMH,DCA,...,<NA>,0.0,50.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
2,2022.0,1.0,16.0,7.0,2022-01-16,YX,N412YX,4879.0,CMH,DCA,...,<NA>,0.0,53.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
3,2022.0,1.0,17.0,1.0,2022-01-17,YX,N405YX,4879.0,CMH,DCA,...,<NA>,0.0,56.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN
4,2022.0,1.0,18.0,2.0,2022-01-18,YX,N420YX,4879.0,CMH,DCA,...,<NA>,0.0,48.0,1.0,323.0,NaN,NaN,NaN,NaN,NaN

In [17]:
print(f"The smaller dataset has {len(flights)/1e6} million rows")

The smaller dataset has 0.537902 million rows

In these next two visualizations, Datashader data is displayed on the plots.
As we pan and zoom, Datashader recomputes the appropriate pixel shades using Dask.

This allows us to easily look at the entire 30 million row dataset, but still
zoom into a single point, without requiring downsampling or decimation of the dataset.

In [18]:
!pip install datashader

Requirement already satisfied: datashader in /usr/local/lib/python3.13/dist-packages (0.19.1)
Requirement already satisfied: colorcet in /usr/local/lib/python3.13/dist-packages (from datashader) (3.2.1)
Requirement already satisfied: multipledispatch in /usr/local/lib/python3.13/dist-packages (from datashader) (1.0.0)
Requirement already satisfied: numba in /usr/local/lib/python3.13/dist-packages (from datashader) (0.61.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from datashader) (2.1.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from datashader) (26.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from datashader) (2.2.3)
Requirement already satisfied: param in /usr/local/lib/python3.13/dist-packages (from datashader) (2.4.1)
Requirement already satisfied: pyct in /usr/local/lib/python3.13/dist-packages (from datashader) (0.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from datashader) (2.32.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from datashader) (1.16.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.13/dist-packages (from datashader) (0.12.1)
Requirement already satisfied: xarray in /usr/local/lib/python3.13/dist-packages (from datashader) (2025.12.0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba->datashader) (0.44.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->datashader) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->datashader) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->datashader) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->datashader) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->datashader) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->datashader) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->datashader) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->datashader) (1.17.0)

In [19]:
import hvplot.dask
import panel as pn
pn.extension()

In [20]:
flights['FlightDate'] = dd.to_datetime(flights['FlightDate'])
flights.hvplot.line(x='FlightDate', y='DepDelay', datashade=True)

BokehModel(combine_events=True, render_bundle={'docs_json': {'f14ed8f0-bdae-4303-b2e4-61e760bee94d': {'version…

In [21]:
import pandas as pd
import hvplot.pandas

# Gom nhóm tính trung bình DepDelay theo FlightDate và chuyển về Pandas
daily_df = flights.groupby('FlightDate')['DepDelay'].mean().compute().reset_index()
daily_df['FlightDate'] = pd.to_datetime(daily_df['FlightDate'])

# Vẽ biểu đồ đường
daily_df.hvplot.line(x='FlightDate', y='DepDelay', title="Trung bình phút trễ theo ngày")

:Curve   [FlightDate]   (DepDelay)

In [22]:
flights[['ArrDelay', 'Distance']].hvplot.scatter(x='ArrDelay', y='Distance', datashade=True)

BokehModel(combine_events=True, render_bundle={'docs_json': {'b6b323dc-d60b-4a06-a885-4895df1b9d04': {'version…

In [ ]:
# To shutdown the cluster, uncomment and run the next line
# cluster.shutdown()

---

## Next →

[Big data dashboards](./07-big-data-dashboards.ipynb)