<img src="images/polars-logo.svg" width="25%" align="right">

# Blazingly-fast DataFrames with Polars

In this notebook, we'll get a high-level understanding of Polars by exploring ~1 year the airline on-time performance data.

---

[Polars](https://docs.pola.rs) is a relatively new, but increasingly popular library for manipulating structured data. With a Rust-based core query engine, it is designed for efficient, out-of-core, and parallel operations.

## Read a Parquet file

Polars has a strict grammar and composable API, as we will see in the following section.

But to begin with, there are some similarities with the pandas API.
For instance, you can use the similar `read_parquet`, `read_csv`, syntax for I/O, and `head`, `shape`, `column` to inspect the DataFrame.

In [1]:
!pip install -q polars

In [2]:
import polars as pl

In [ ]:
import os
import io
import zipfile
import requests
import polars as pl

url = "https://transtats.bts.gov/PREZIP/On_Time_Reporting_Carrier_On_Time_Performance_1987_present_2022_1.zip"

r = requests.get(url)
r.raise_for_status()

with zipfile.ZipFile(io.BytesIO(r.content)) as z:
    csv_file = [f for f in z.namelist() if f.endswith(".csv")][0]
    z.extract(csv_file, "/content")

source = os.path.join("/content", csv_file)

df = pl.read_csv(source)

print("Đã tải file:")
print(source)
print("Shape:", df.shape)

Đã tải file:
/content/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv
Shape: (537902, 110)

In [ ]:
df.head()

shape: (5, 110)
┌──────┬─────────┬───────┬────────────┬───┬──────────────────┬───────────────┬─────────────┬──────┐
│ Year ┆ Quarter ┆ Month ┆ DayofMonth ┆ … ┆ Div5LongestGTime ┆ Div5WheelsOff ┆ Div5TailNum ┆      │
│ ---  ┆ ---     ┆ ---   ┆ ---        ┆   ┆ ---              ┆ ---           ┆ ---         ┆ ---  │
│ i64  ┆ i64     ┆ i64   ┆ i64        ┆   ┆ str              ┆ str           ┆ str         ┆ str  │
╞══════╪═════════╪═══════╪════════════╪═══╪══════════════════╪═══════════════╪═════════════╪══════╡
│ 2022 ┆ 1       ┆ 1     ┆ 14         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 15         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 16         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 17         ┆ … ┆ null             ┆               ┆             ┆ null │
│ 2022 ┆ 1       ┆ 1     ┆ 18         ┆ … ┆ null             ┆               ┆             ┆ null │
└──────┴─────────┴───────┴────────────┴───┴──────────────────┴───────────────┴─────────────┴──────┘

In [ ]:
df.shape

(537902, 110)

In [ ]:
df.columns[:10]

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number']

## Expression system

The expression system is one of the most powerful concepts in Polars.

Before we look into expressions, let's walk through the building blocks: `select`, `filter`, `group_by`, and `with_columns`.

### Building blocks

#### Let's `select` a subset of columns

In [ ]:
columns = [
    'Year', 'Month', 'DayofMonth', 'DayOfWeek', 'FlightDate', 'Reporting_Airline',
    'Tail_Number', 'Flight_Number_Reporting_Airline', 'Origin', 'Dest', 'CRSDepTime',
    'DepTime', 'DepDelay', 'ArrTime', 'ArrDelay', 'Cancelled',
    'CancellationCode', 'Diverted', 'AirTime', 'Flights', 'Distance',
]

In [ ]:
df = df.select(pl.col(columns))

In [ ]:
df.columns

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1WheelsOn',
 'Div1TotalGTime',
 'Div1LongestGTime',
 'Div1WheelsOff',
 'Div1TailNum',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum',
 '']

#### Let's `filter` for the "DL" carrier

In [ ]:
df.filter((pl.col("Reporting_Airline") == "DL"))

shape: (68_963, 21)
┌──────┬───────┬────────────┬───────────┬───┬──────────┬─────────┬─────────┬──────────┐
│ Year ┆ Month ┆ DayofMonth ┆ DayOfWeek ┆ … ┆ Diverted ┆ AirTime ┆ Flights ┆ Distance │
│ ---  ┆ ---   ┆ ---        ┆ ---       ┆   ┆ ---      ┆ ---     ┆ ---     ┆ ---      │
│ i64  ┆ i64   ┆ i64        ┆ i64       ┆   ┆ f64      ┆ f64     ┆ f64     ┆ f64      │
╞══════╪═══════╪════════════╪═══════════╪═══╪══════════╪═════════╪═════════╪══════════╡
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ null    ┆ 1.0     ┆ 1076.0   │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 93.0    ┆ 1.0     ┆ 581.0    │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 83.0    ┆ 1.0     ┆ 581.0    │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 93.0    ┆ 1.0     ┆ 680.0    │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 60.0    ┆ 1.0     ┆ 341.0    │
│ …    ┆ …     ┆ …          ┆ …         ┆ … ┆ …        ┆ …       ┆ …       ┆ …        │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 94.0    ┆ 1.0     ┆ 554.0    │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 169.0   ┆ 1.0     ┆ 1145.0   │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 102.0   ┆ 1.0     ┆ 577.0    │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 46.0    ┆ 1.0     ┆ 226.0    │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 0.0      ┆ 102.0   ┆ 1.0     ┆ 630.0    │
└──────┴───────┴────────────┴───────────┴───┴──────────┴─────────┴─────────┴──────────┘

#### Find the number of entries for each day of the week (`groupby`)

In [ ]:
df.group_by("DayOfWeek").len()

shape: (7, 2)
┌───────────┬───────┐
│ DayOfWeek ┆ len   │
│ ---       ┆ ---   │
│ i64       ┆ u32   │
╞═══════════╪═══════╡
│ 5         ┆ 73786 │
│ 6         ┆ 75809 │
│ 4         ┆ 73422 │
│ 7         ┆ 90343 │
│ 1         ┆ 91367 │
│ 2         ┆ 65914 │
│ 3         ┆ 67261 │
└───────────┴───────┘

#### Create a new column with  "DISTANCE" values in kilometers instead of miles (`with_columns`)

In [ ]:
df.with_columns((pl.col("Distance")*1.609344).alias("DISTANCE_KM"))

shape: (537_902, 22)
┌──────┬───────┬────────────┬───────────┬───┬─────────┬─────────┬──────────┬─────────────┐
│ Year ┆ Month ┆ DayofMonth ┆ DayOfWeek ┆ … ┆ AirTime ┆ Flights ┆ Distance ┆ DISTANCE_KM │
│ ---  ┆ ---   ┆ ---        ┆ ---       ┆   ┆ ---     ┆ ---     ┆ ---      ┆ ---         │
│ i64  ┆ i64   ┆ i64        ┆ i64       ┆   ┆ f64     ┆ f64     ┆ f64      ┆ f64         │
╞══════╪═══════╪════════════╪═══════════╪═══╪═════════╪═════════╪══════════╪═════════════╡
│ 2022 ┆ 1     ┆ 14         ┆ 5         ┆ … ┆ 63.0    ┆ 1.0     ┆ 323.0    ┆ 519.818112  │
│ 2022 ┆ 1     ┆ 15         ┆ 6         ┆ … ┆ 50.0    ┆ 1.0     ┆ 323.0    ┆ 519.818112  │
│ 2022 ┆ 1     ┆ 16         ┆ 7         ┆ … ┆ 53.0    ┆ 1.0     ┆ 323.0    ┆ 519.818112  │
│ 2022 ┆ 1     ┆ 17         ┆ 1         ┆ … ┆ 56.0    ┆ 1.0     ┆ 323.0    ┆ 519.818112  │
│ 2022 ┆ 1     ┆ 18         ┆ 2         ┆ … ┆ 48.0    ┆ 1.0     ┆ 323.0    ┆ 519.818112  │
│ …    ┆ …     ┆ …          ┆ …         ┆ … ┆ …       ┆ …       ┆ …        ┆ …           │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 94.0    ┆ 1.0     ┆ 554.0    ┆ 891.576576  │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 169.0   ┆ 1.0     ┆ 1145.0   ┆ 1842.69888  │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 102.0   ┆ 1.0     ┆ 577.0    ┆ 928.591488  │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 46.0    ┆ 1.0     ┆ 226.0    ┆ 363.711744  │
│ 2022 ┆ 1     ┆ 6          ┆ 4         ┆ … ┆ 102.0   ┆ 1.0     ┆ 630.0    ┆ 1013.88672  │
└──────┴───────┴────────────┴───────────┴───┴─────────┴─────────┴──────────┴─────────────┘

### Expressions & Context

> An expression is a tree of operations that describe how to construct one or more Series. As the outputs are Series, it is straightforward to apply a sequence of expressions (similar to method chaining in pandas) each of which transforms the output from the previous step.
>
> ~ [Expressions - Polars documentation](https://docs.pola.rs/user-guide/concepts/expressions/)

Expressions allow you to decouple the logic from execution, and Polars can optimize and parallelize the expressions.

A related concept ins **Context**:

> A context, as implied by the name, refers to the context in which an expression needs to be evaluated. There are three main contexts:
>
> * Selection: df.select(...), df.with_columns(...)
> * Filtering: df.filter()
> * Group by / Aggregation: df.group_by(...).agg(...)
>
> ~ [Context - Polars documentation](https://docs.pola.rs/user-guide/concepts/contexts/)

Let's understand these with some example computations similar to the initial pandas and Dask computations:

#### What are the mean & median, arrival and departure delays?

The expression would be:

In [ ]:
(
    pl.col("DepDelay", "ArrDelay").mean()
)

Now, you can apply this expression to any DataFrame with `select`, putting this in the "selection" context:

In [ ]:
df.select(pl.col("DepDelay", "ArrDelay").mean())

shape: (1, 2)
┌───────────┬──────────┐
│ DepDelay  ┆ ArrDelay │
│ ---       ┆ ---      │
│ f64       ┆ f64      │
╞═══════════╪══════════╡
│ 10.932093 ┆ 3.981085 │
└───────────┴──────────┘

You can provide several expressions, and they will be executed in parallel:

In [ ]:
# executed in parallel
df.select(
    pl.col("DepDelay").mean().alias("MEAN_DEP_DELAY"),
    pl.col("DepDelay").median().alias("MEDIAN_DEP_DELAY"),
    pl.col("ArrDelay").mean().alias("MEAN_ARR_DELAY"),
    pl.col("ArrDelay").median().alias("MEDAIN_ARR_DELAY"),
)

shape: (1, 4)
┌────────────────┬──────────────────┬────────────────┬──────────────────┐
│ MEAN_DEP_DELAY ┆ MEDIAN_DEP_DELAY ┆ MEAN_ARR_DELAY ┆ MEDAIN_ARR_DELAY │
│ ---            ┆ ---              ┆ ---            ┆ ---              │
│ f64            ┆ f64              ┆ f64            ┆ f64              │
╞════════════════╪══════════════════╪════════════════╪══════════════════╡
│ 10.932093      ┆ -2.0             ┆ 3.981085       ┆ -8.0             │
└────────────────┴──────────────────┴────────────────┴──────────────────┘

#### 💻 Your turn: Find the mean arrival and departure delays for each airline

Hint: Use `df.group_by(...).agg(...)`

In [ ]:
# Your code here. When ready, click on the three dots for the solutions.
df.group_by("Reporting_Airline").agg(
    pl.col("DepDelay").mean(),
    pl.col("ArrDelay").mean(),
)

shape: (17, 3)
┌───────────────────┬───────────┬───────────┐
│ Reporting_Airline ┆ DepDelay  ┆ ArrDelay  │
│ ---               ┆ ---       ┆ ---       │
│ str               ┆ f64       ┆ f64       │
╞═══════════════════╪═══════════╪═══════════╡
│ YX                ┆ 6.944988  ┆ 3.306272  │
│ HA                ┆ 9.558308  ┆ 6.88422   │
│ OH                ┆ 14.828111 ┆ 10.698828 │
│ AA                ┆ 7.928395  ┆ -1.075832 │
│ YV                ┆ 18.966965 ┆ 11.159476 │
│ …                 ┆ …         ┆ …         │
│ MQ                ┆ 5.140703  ┆ -1.326464 │
│ NK                ┆ 11.747568 ┆ 8.520168  │
│ AS                ┆ 8.076828  ┆ 5.233294  │
│ B6                ┆ 23.401837 ┆ 18.721082 │
│ QX                ┆ 12.158578 ┆ 10.964571 │
└───────────────────┴───────────┴───────────┘

In [ ]:
df.group_by("Reporting_Airline").agg(
     pl.col("DepDelay").mean(),
     pl.col("ArrDelay").mean(),
)

shape: (17, 3)
┌───────────────────┬───────────┬───────────┐
│ Reporting_Airline ┆ DepDelay  ┆ ArrDelay  │
│ ---               ┆ ---       ┆ ---       │
│ str               ┆ f64       ┆ f64       │
╞═══════════════════╪═══════════╪═══════════╡
│ YX                ┆ 6.944988  ┆ 3.306272  │
│ UA                ┆ 13.073434 ┆ 4.75627   │
│ F9                ┆ 15.565161 ┆ 10.955163 │
│ G4                ┆ 12.150682 ┆ 12.243135 │
│ MQ                ┆ 5.140703  ┆ -1.326464 │
│ …                 ┆ …         ┆ …         │
│ OO                ┆ 14.785588 ┆ 7.928475  │
│ DL                ┆ 7.864645  ┆ -0.228486 │
│ HA                ┆ 9.558308  ┆ 6.88422   │
│ NK                ┆ 11.747568 ┆ 8.520168  │
│ QX                ┆ 12.158578 ┆ 10.964571 │
└───────────────────┴───────────┴───────────┘

## Lazy evaluation

Similar to Dask, Polars also supports lazy evaluation.

A lazily evaluated DataFrame is called the `LazyFrame` in Polars. Expressions operate the same in lazy and eager mode.

To create a `LazyFrame`, we use `scan_parquet` (instead of `read_parquet`):

In [ ]:
source = "/content/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv"
df_lazy = pl.scan_csv(source)

In [ ]:
df_lazy

`LazyFrame`s have an explain method, where "PROJECT" refers to the number of columns Polars will operate on.

In [ ]:
print(df_lazy.explain())

Csv SCAN [/content/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv]
PROJECT */110 COLUMNS
ESTIMATED ROWS: 519340

### Re-compute mean & median, arrival and departure delays

In [ ]:
df_lazy.select(
    pl.col("DepDelay").mean().alias("MEAN_DEP_DELAY"),
    pl.col("DepDelay").median().alias("MEDIAN_DEP_DELAY"),
    pl.col("ArrDelay").mean().alias("MEAN_ARR_DELAY"),
    pl.col("ArrDelay").median().alias("MEDAIN_ARR_DELAY"),
)

Now, on `.explain`, PROJECT shows 2/109 COLUMNS:

In [ ]:
df_lazy.select(
    pl.col("DepDelay").mean().alias("MEAN_DEP_DELAY"),
    pl.col("DepDelay").median().alias("MEDIAN_DEP_DELAY"),
    pl.col("ArrDelay").mean().alias("MEAN_ARR_DELAY"),
    pl.col("ArrDelay").median().alias("MEDAIN_ARR_DELAY"),
).explain()

'SELECT [col("DepDelay").mean().alias("MEAN_DEP_DELAY"), col("DepDelay").median().alias("MEDIAN_DEP_DELAY"), col("ArrDelay").mean().alias("MEAN_ARR_DELAY"), col("ArrDelay").median().alias("MEDAIN_ARR_DELAY")]\n  Csv SCAN [/content/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2022_1.csv]\n  PROJECT 2/110 COLUMNS\n  ESTIMATED ROWS: 519340'

`.collect()` perform the computation and returns the result eagerly:

In [ ]:
df_lazy.select(
    pl.col("DepDelay").mean().alias("MEAN_DEP_DELAY"),
    pl.col("DepDelay").median().alias("MEDIAN_DEP_DELAY"),
    pl.col("ArrDelay").mean().alias("MEAN_ARR_DELAY"),
    pl.col("ArrDelay").median().alias("MEDAIN_ARR_DELAY"),
).collect()

shape: (1, 4)
┌────────────────┬──────────────────┬────────────────┬──────────────────┐
│ MEAN_DEP_DELAY ┆ MEDIAN_DEP_DELAY ┆ MEAN_ARR_DELAY ┆ MEDAIN_ARR_DELAY │
│ ---            ┆ ---              ┆ ---            ┆ ---              │
│ f64            ┆ f64              ┆ f64            ┆ f64              │
╞════════════════╪══════════════════╪════════════════╪══════════════════╡
│ 10.932093      ┆ -2.0             ┆ 3.981085       ┆ -8.0             │
└────────────────┴──────────────────┴────────────────┴──────────────────┘

Finally, you can also `.profile()` the compute to find areas for optimization:

In [ ]:
df_lazy.select(
    pl.col("DepDelay").mean().alias("MEAN_DEP_DELAY"),
    pl.col("DepDelay").median().alias("MEDIAN_DEP_DELAY"),
    pl.col("ArrDelay").mean().alias("MEAN_ARR_DELAY"),
    pl.col("ArrDelay").median().alias("MEDAIN_ARR_DELAY"),
).profile()

(shape: (1, 4)
 ┌────────────────┬──────────────────┬────────────────┬──────────────────┐
 │ MEAN_DEP_DELAY ┆ MEDIAN_DEP_DELAY ┆ MEAN_ARR_DELAY ┆ MEDAIN_ARR_DELAY │
 │ ---            ┆ ---              ┆ ---            ┆ ---              │
 │ f64            ┆ f64              ┆ f64            ┆ f64              │
 ╞════════════════╪══════════════════╪════════════════╪══════════════════╡
 │ 10.932093      ┆ -2.0             ┆ 3.981085       ┆ -8.0             │
 └────────────────┴──────────────────┴────────────────┴──────────────────┘,
 shape: (2, 3)
 ┌─────────────────────────────────┬────────┬────────┐
 │ node                            ┆ start  ┆ end    │
 │ ---                             ┆ ---    ┆ ---    │
 │ str                             ┆ u64    ┆ u64    │
 ╞═════════════════════════════════╪════════╪════════╡
 │ optimization                    ┆ 0      ┆ 212420 │
 │ select(MEAN_DEP_DELAY, MEDIAN_… ┆ 212420 ┆ 224350 │
 └─────────────────────────────────┴────────┴────────┘)

## Limitations

### Polars is design for efficient columnar operations

Hence, `axis=1` operations have limited support, and may be efficient than array libraries.

If you have only numerical data, convert to NumPy (`.to_numpy()`)

### Incomplete support for full pandas API

You may find some functionality which is only available in pandas, and not (yet) in Polars.

In that case, you can easily convert to pandas:

- `.to_pandas()`: probably copies data
- `.to_pandas(use_pyarrow_extension_array=True)`: zero-copy, but pandas support for pyarrow is still flaky

---

## Next →

Let's learn about [DuckDB](11-duckdb.ipynb)!